export const complaintNature = [
  "Consumer complaints",
  "Police complaints",
  "Landlord-tenant complaints",
  "Employment complaints",
  "Traffic complaints",
  "Corruption complaints",
  "Tax complaints",
  "Education complaints",
  "Medical complaints",
  "Banking and finance complaints",
  "Electricity complaints",
  "Environmental complaints",
  "Telecommunications complaints",
  "Insurance complaints",
  "Housing complaints",
  "Cybercrime complaints",
  "Missing person cases",
  "Domestic violence complaints",
];

export const districts = [
  "Alappuzha",
  "Ernakulam",
  "Idukki",
  "Kannur",
  "Kasaragod",
  "Kollam",
  "Kottayam",
  "Kozhikode",
  "Malappuram",
  "Palakkad",
  "Pathanamthitta",
  "Thiruvananthapuram",
  "Thrissur",
  "Wayanad",
];
